
development:
  adapter: postgresql
  database: randur_development
  pool: 20
  timeout: 5000

test:
  adapter: postgresql
  database: randur_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: randur
  pool: 5
  timeout: 5000
